# Generated by Django 5.1.3 on 2024-11-07 09:33sqlite3 db.sqlite3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buying', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.customuserentity'),
        ),
        migrations.AddField(
            model_name='cartitementity',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='buying.cartentity'),
        ),
        migrations.AddField(
            model_name='cartitementity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productentity'),
        ),
        migrations.AddField(
            model_name='orderentity',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buying.cartentity'),
        ),
        migrations.AddField(
            model_name='orderentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuserentity'),
        ),
    ]
