# Generated by Django 5.1.3 on 2024-11-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartentity',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderEntity',
        ),
    ]
